[versions]
derby-version = "10.17.1.0"
file-worker-version = "19.0"
gradle-plugin-grgit-version = "5.3.0"
gradle-plugin-license-version = "0.16.1"
gradle-plugin-lombok-version = "8.11"
gradle-plugin-spotless-version = "7.0.0.BETA4"
gradle-plugin-version-catalog-update-version = "0.8.5"
gradle-plugin-versions-version = "0.51.0"
gradle-versions-plugin-version = "0.51.0"
grgit-gradle-version = "5.2.2"
h2-version = "2.3.232"
hsqldb-version = "2.7.4"
junit-jupiter-version = "5.11.3"
junit-platform-launcher-version = "1.11.3"
license-gradle-plugin-version = "0.16.1"
lombok-plugin-version = "8.6"
lombok-version = "1.18.36"
meanbean-version = "3.0.0-M9"
mysql-connector-java-version = "8.0.33"
postgresql-version = "42.7.4"
spotless-plugin-gradle-version = "6.25.0"
spring-context-version = "6.2.0"
spring-orm-version = "6.2.0"
sqlite-jdbc-version = "3.47.1.0"

[libraries]
derby = { module = "org.apache.derby:derby", version.ref = "derby-version" }
file-worker = { module = "io.github.astrapi69:file-worker", version.ref = "file-worker-version" }
h2 = { module = "com.h2database:h2", version.ref = "h2-version" }
hsqldb = { module = "org.hsqldb:hsqldb", version.ref = "hsqldb-version" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter-version" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform-launcher-version" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok-version" }
meanbean = { module = "com.github.meanbeanlib:meanbean", version.ref = "meanbean-version" }
mysql-connector-java = { module = "mysql:mysql-connector-java", version.ref = "mysql-connector-java-version" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql-version" }
spring-context = { module = "org.springframework:spring-context", version.ref = "spring-context-version" }
spring-orm = { module = "org.springframework:spring-orm", version.ref = "spring-orm-version" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc-version" }

[bundles]
# Dependencies for the annotation processor used during the compilation process
annotation-processor = [
    "lombok",
]
# Dependencies required only at compile-time and not included in the final artifact
compile-only = [
    "lombok",
]
# The core dependencies
core-dependencies = [
    "spring-orm",
    "spring-context"
]
# Annotation processor dependencies used specifically for test classes
test-annotation-processor = [
    "lombok",
]
# Dependencies required only at test compile-time and not included in test runtime
test-compile-only = [
    "lombok",
]
# Dependencies required only at test runtime, such as test execution platforms
test-runtime-only = [
    "junit-platform-launcher",
]
# Dependencies required for unit testing
unit-testing = [
    "file-worker",
    "junit-jupiter",
    "meanbean",
    "derby",
    "sqlite-jdbc",
    "hsqldb",
    "h2",
    "postgresql",
    "mysql-connector-java"
]

[plugins]
gradle-versions-plugin = { id = "com.github.ben-manes.versions", version.ref = "gradle-plugin-versions-version" }
grgit-gradle = { id = "org.ajoberstar.grgit", version.ref = "gradle-plugin-grgit-version" }
license-gradle-plugin = { id = "com.github.hierynomus.license", version.ref = "gradle-plugin-license-version" }
lombok-plugin = { id = "io.freefair.lombok", version.ref = "gradle-plugin-lombok-version" }
spotless-plugin-gradle = { id = "com.diffplug.spotless", version.ref = "gradle-plugin-spotless-version" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "gradle-plugin-version-catalog-update-version" }
